### ISSUE TITLE
CRACO now supports Create React App 5 

### ISSUE THREAD

**Issue by criszz77** [criszz77/luna#59]
CRACO now supports Create React App 5 and it has some shiny new docs: https://craco.js.org/

https://github.com/dilanx/craco/issues/426#issuecomment-1307319525

**Comment by mikehardy** [comment]
Yeah - I have been waiting on that release before really digging in here, and wanted to ask you what you thought.
Back to CRACO, or stay with result of #54 / react-app-rewired ?

**Comment by criszz77** [comment]
Although I really can't test the two at the moment against each other to see which one is a winner, I would definitely bet on the new CRACO maintainer, he seems very passionate and it looks like he worked very hard for this update.

**Comment by mikehardy** [comment]
Hmm - just checked "code frequency" and "contributors" for both, craco does seem more active.
Both had single person maintenance, it seemed to me, with react-app-rewired's maintainer currently mostly dormant and a fresh maintainer on craco
So on balance I think craco,  but I'm not sure what it would take to unwind the change from #54 so please don't take that as any guess even on whether it is worth it to change back. I am just thinking out loud since you and I collaborate some that way - at the non-concrete "what's better..." level

**Comment by criszz77** [comment]
I'll give it a shot, I'm pretty sure it won't take me more than 1-2 hours to make the change. I already did something with #46 as well, but I've been pretty busy at work. I hope to open a PR this weekend on both of the issues.

**Comment by criszz77** [comment]
Unfortunately I'll reopen the issue since I still didn't manage to use the `metro-react-native-babel-preset` with CRACO :/

**Comment by criszz77** [comment]
Since now we're using the Next.js cool build tools, we no longer need CRACO or react-app-rewired. 🎉
